### ISSUE TITLE
Create milestones and labels

### ISSUE THREAD

**Issue by amavalankar** [InspirationRobotics/inspiration_ftc#44]
### Milestones will organize our repository and help get a schedule for tasks

- [ ] Work with @aktang to set milestones (week to specify when task should be complete)

- [ ] Also make labels (mechanical, P1, P2, P3, etc.) Some may already exist, so just update them.

- [ ] Click [here](https://github.com/InspirationRobotics/inspiration_ftc/milestones) to add milestones
