### ISSUE TITLE
Position tracking system using encoders that allows the robot to be aware of its own position (precursor to full odometry)

### ISSUE THREAD

**Issue by risih** [InspirationRobotics/inspiration_ftc#78]
- [ ] Write the procedure to normalize headings
- [ ] Write the procedure to recalculate global position and have the encoder procedures call them whenever they are called
- [ ] Write procedure to navigate to X and Y coordinates
